In [443]:
import pandas 
pandas.__version__

'1.0.1'

In [444]:
import pandas as pd
import numpy as np

In [445]:
data = pd.Series([1.22,323.2,0.4,2.2])
data

0      1.22
1    323.20
2      0.40
3      2.20
dtype: float64

In [446]:
data.values

array([  1.22, 323.2 ,   0.4 ,   2.2 ])

In [447]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [448]:
data[1]

323.2

In [449]:
data[1:3]

1    323.2
2      0.4
dtype: float64

In [450]:
data = pd.Series([1,2,3,4,5,6],index=  ['a','b','c','d','e','f'])

In [451]:
data

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [452]:
data['b']

2

In [453]:
population = {'india': 4000,'uk':20000,'italy':500000,'china':400000}

In [454]:
pop = pd.Series(population)
pop

india      4000
uk        20000
italy    500000
china    400000
dtype: int64

In [455]:
pop.min

<bound method Series.min of india      4000
uk        20000
italy    500000
china    400000
dtype: int64>

In [456]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [457]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [458]:
pd.Series({2:'a',1:'b',3:'c'},index= [3,2])

3    c
2    a
dtype: object

In [459]:
area = pd.Series(population)
area

india      4000
uk        20000
italy    500000
china    400000
dtype: int64

In [460]:
state  =pd.DataFrame({'population': population,'area':area})
state

population    area
china      400000  400000
india        4000    4000
italy      500000  500000
uk          20000   20000

In [461]:
state.index

Index(['china', 'india', 'italy', 'uk'], dtype='object')

In [462]:
data = [{'a':i,'b':2*i} for i in range(3)]

In [463]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [464]:
pd.DataFrame ([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [465]:
pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])

foo       bar
a  0.334745  0.451281
b  0.254328  0.966875
c  0.019069  0.164374

In [466]:
a = np.zeros(3,dtype=[('a','i8'),('b','f8')])

In [467]:
a

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('a', '<i8'), ('b', '<f8')])

In [468]:
pd.DataFrame(a)

a    b
0  0  0.0
1  0  0.0
2  0  0.0

In [469]:
ind = pd.Index([2,3,4,5,6],dtype = 'int8')
ind

Int64Index([2, 3, 4, 5, 6], dtype='int64')

In [470]:
ind[1]

3

In [471]:
ind[::2]

Int64Index([2, 4, 6], dtype='int64')

In [472]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [473]:
inda = pd.Index([1,3,5,7,9])

In [474]:
indb = pd.Index([2,3,5,7,99])

In [475]:
inda&indb

Int64Index([3, 5, 7], dtype='int64')

In [476]:
inda|indb

Int64Index([1, 2, 3, 5, 7, 9, 99], dtype='int64')

In [477]:
inda^indb

Int64Index([1, 2, 9, 99], dtype='int64')

In [478]:
data = pd.Series([1.,2,3,4,5,6],index=['a','b','c','d','e','f'])
data

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
dtype: float64

In [479]:
data['b']

2.0

In [480]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [481]:
data.values

array([1., 2., 3., 4., 5., 6.])

In [482]:
list(data.items())

[('a', 1.0), ('b', 2.0), ('c', 3.0), ('d', 4.0), ('e', 5.0), ('f', 6.0)]

In [483]:
data['d'] = 1.222
data

a    1.000
b    2.000
c    3.000
d    1.222
e    5.000
f    6.000
dtype: float64

In [484]:
data['a':'c']

a    1.0
b    2.0
c    3.0
dtype: float64

In [485]:
data[0:2]

a    1.0
b    2.0
dtype: float64

In [486]:
data[(data>1.0)&(data<3)]

b    2.000
d    1.222
dtype: float64

In [487]:
data[['a','e']]


a    1.0
e    5.0
dtype: float64

In [488]:
data = pd.Series(['a','b','c'],index=[1,3,5])

In [489]:
data

1    a
3    b
5    c
dtype: object

In [490]:
data[3]#explicit

'b'

In [491]:
data[1:3] #implicite

3    b
5    c
dtype: object

In [492]:
data.loc[1]

'a'

In [493]:
data.loc[1:5]

1    a
3    b
5    c
dtype: object

In [494]:
data.iloc[1]

'b'

In [495]:
data.iloc[1:]

3    b
5    c
dtype: object

In [496]:
data.iloc[1:4]

3    b
5    c
dtype: object

In [497]:
area = pd.Series({'California': 423967, 'Texas': 695662,
 'New York': 141297, 'Florida': 170312,
 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127, 'Florida': 19552860,
 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [498]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [499]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [500]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [501]:
data.pop

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [502]:
data ['density'] = data['pop']/data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [503]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [504]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [505]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [506]:
data.loc[:'New York',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [507]:
data.loc[data.density>100,['pop','density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [508]:
data.iloc[0,2]
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [509]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [510]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['a','s','c','f'])
df

a  s  c  f
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [511]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [512]:
np.sin(df*np.pi/4)

a             s         c             f
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [513]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127}, name='population')

In [514]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [515]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [516]:
a = pd.Series([2,3,4],index=[0,1,2])
b = pd.Series([22,33,44],index=[1,2,3])

In [517]:
a+b

0     NaN
1    25.0
2    37.0
3     NaN
dtype: float64

In [518]:
a.add(b,fill_value=0)

0     2.0
1    25.0
2    37.0
3    44.0
dtype: float64

In [519]:
a =rng.randint(10,size=(3,4))
a

array([[1, 7, 5, 1],
       [4, 0, 9, 5],
       [8, 0, 9, 2]])

In [520]:
a[1]

array([4, 0, 9, 5])

In [521]:
a-a[1]

array([[-3,  7, -4, -4],
       [ 0,  0,  0,  0],
       [ 4,  0,  0, -3]])

In [522]:
df = pd.DataFrame(a,columns=list('QRST'))
df

Q  R  S  T
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [523]:
df.iloc[2]

Q    8
R    0
S    9
T    2
Name: 2, dtype: int32

In [524]:
df.subtract(df['R'],axis =0)

Q  R  S  T
0 -6  0 -2 -6
1  4  0  9  5
2  8  0  9  2

In [525]:
df.iloc[0,::2]

Q    1
S    5
Name: 0, dtype: int32

In [526]:
#Python Missing Data

In [527]:
val = np.array([1,None,3,4])
val

array([1, None, 3, 4], dtype=object)

In [528]:
for dtype in ['object','int']:
    print("dtype =",dtype)
    %timeit np.arange(1E6,dtype = dtype).sum()
    print()

dtype = object
266 ms ± 4.36 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype = int
13.3 ms ± 276 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [529]:
value = np.array([1,np.nan,3,4])
value.dtype

dtype('float64')

In [530]:
value

array([ 1., nan,  3.,  4.])

In [531]:
1 + np.nan

nan

In [532]:
np.nansum(value),np.nanmin(value),np.nanmax(value)

(8.0, 1.0, 4.0)

In [533]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [534]:
x = pd.Series(range(2))
x

0    0
1    1
dtype: int64

In [535]:
data = pd.Series([1,np.nan,'hellow',None])
data

0         1
1       NaN
2    hellow
3      None
dtype: object

In [536]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [537]:
data[data.notnull()]

0         1
2    hellow
dtype: object

In [538]:
data.dropna()

0         1
2    hellow
dtype: object

In [539]:
df  = pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [540]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [541]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [542]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [543]:
df.dropna(axis = 'columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [544]:
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [545]:
data 

0         1
1       NaN
2    hellow
3      None
dtype: object

In [546]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [547]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [548]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [549]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [550]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [551]:
df.fillna(method ='ffill',axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [552]:
index = [('California', 2000), ('California', 2010),
 ('New York', 2000), ('New York', 2010),
 ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
 18976457, 19378102,
 20851820, 25145561]

In [553]:
pop = pd.Series(populations, index = index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [554]:
pop[[i for i in pop.index if i[1]==2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [555]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [556]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [557]:
pop[:,2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [558]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [559]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [560]:
pop_df = pd.DataFrame({'total': pop,'under' : [21211,434,4323342,12121,656,889]})
pop_df

total    under
California 2000  33871648    21211
           2010  37253956      434
New York   2000  18976457  4323342
           2010  19378102    12121
Texas      2000  20851820      656
           2010  25145561      889

In [561]:
f1 = pop_df['under']/pop_df['total']
f1.unstack()

2000      2010
California  0.000626  0.000012
New York    0.227827  0.000625
Texas       0.000031  0.000035

In [562]:
df = pd.DataFrame(np.random.rand(4, 2),
 index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
 columns=['data1', 'data2'])
df

data1     data2
a 1  0.698409  0.214995
  2  0.166356  0.030911
b 1  0.387202  0.260013
  2  0.399193  0.283836

In [563]:
data = {('California', 2000): 33871648,
 ('California', 2010): 37253956,
 ('Texas', 2000): 20851820,
 ('Texas', 2010): 25145561,
 ('New York', 2000): 18976457,
 ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [564]:
pd.MultiIndex.from_arrays([['a','b','c','d'],[1,2,3,4]])

MultiIndex([('a', 1),
            ('b', 2),
            ('c', 3),
            ('d', 4)],
           )

In [565]:
 pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [566]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [567]:
pop.index.names = ['state','year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [568]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
 names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
 names=['subject', 'type'])

In [569]:
data = np.round(np.random.randn(4,6),1)
data

array([[ 1.3, -0.5,  1.8, -0.5,  0.3,  0.6],
       [ 0.3, -1. , -0.5,  0.6, -0.2, -0.9],
       [-0.6,  1.3,  0.4,  0.3,  2. ,  1.5],
       [ 1.3,  0.1,  1.3,  0.2,  1.7, -0.3]])

In [570]:
data[:, ::2] *= 10
data+=37

In [571]:
data

array([[50. , 36.5, 55. , 36.5, 40. , 37.6],
       [40. , 36. , 32. , 37.6, 35. , 36.1],
       [31. , 38.3, 41. , 37.3, 57. , 38.5],
       [50. , 37.1, 50. , 37.2, 54. , 36.7]])

In [572]:
h_d = pd.DataFrame(data,index=index,columns = columns)
h_d

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      50.0  36.5  55.0  36.5  40.0  37.6
     2      40.0  36.0  32.0  37.6  35.0  36.1
2014 1      31.0  38.3  41.0  37.3  57.0  38.5
     2      50.0  37.1  50.0  37.2  54.0  36.7

In [573]:
h_d['Sue']

type          HR  Temp
year visit            
2013 1      40.0  37.6
     2      35.0  36.1
2014 1      57.0  38.5
     2      54.0  36.7

In [574]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [575]:
pop ['California', 2000]

33871648

In [576]:
h_d

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      50.0  36.5  55.0  36.5  40.0  37.6
     2      40.0  36.0  32.0  37.6  35.0  36.1
2014 1      31.0  38.3  41.0  37.3  57.0  38.5
     2      50.0  37.1  50.0  37.2  54.0  36.7

In [577]:
h_d.iloc[:2,:3]

subject      Bob       Guido
type          HR  Temp    HR
year visit                  
2013 1      50.0  36.5  55.0
     2      40.0  36.0  32.0

In [578]:
h_d.loc[:,('Guido','Temp')]

year  visit
2013  1        36.5
      2        37.6
2014  1        37.3
      2        37.2
Name: (Guido, Temp), dtype: float64

In [579]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
index

MultiIndex([('a', 1),
            ('a', 2),
            ('c', 1),
            ('c', 2),
            ('b', 1),
            ('b', 2)],
           )

In [580]:
data = pd.Series(np.random.rand(6),index = index)
data

a  1    0.302779
   2    0.347840
c  1    0.007076
   2    0.827436
b  1    0.523459
   2    0.393330
dtype: float64

In [581]:
data.index.names = ['char','int']
data

char  int
a     1      0.302779
      2      0.347840
c     1      0.007076
      2      0.827436
b     1      0.523459
      2      0.393330
dtype: float64

In [582]:
data = data.sort_index()
data

char  int
a     1      0.302779
      2      0.347840
b     1      0.523459
      2      0.393330
c     1      0.007076
      2      0.827436
dtype: float64

In [583]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [584]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [585]:
pop_flat = pop.reset_index(name = 'population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [586]:
pop_flat.set_index(['state','year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [587]:
def make_df(cols,ind):
    """Quick make df"""
    data = {c:[str(c) +str(i) for i in ind] for c in cols}
    print(data)
    return pd.DataFrame(data,ind)
make_df ('ABC',range(3))

{'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2'], 'C': ['C0', 'C1', 'C2']}


A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [588]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [589]:
x = [[1,2],[4,5]]
np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [4, 5, 4, 5]])

In [590]:
df1 = make_df('AB',[1,2])
df2= make_df('AB',[3,4])
print(df1); print(df2); print(pd.concat([df1,df2]))

{'A': ['A1', 'A2'], 'B': ['B1', 'B2']}
{'A': ['A3', 'A4'], 'B': ['B3', 'B4']}
    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [591]:
df3 = make_df('ABCX',[4,5,6,7])
df6 = make_df('HUJK',[22,33,44,55])
print(df3); print(df6); 

{'A': ['A4', 'A5', 'A6', 'A7'], 'B': ['B4', 'B5', 'B6', 'B7'], 'C': ['C4', 'C5', 'C6', 'C7'], 'X': ['X4', 'X5', 'X6', 'X7']}
{'H': ['H22', 'H33', 'H44', 'H55'], 'U': ['U22', 'U33', 'U44', 'U55'], 'J': ['J22', 'J33', 'J44', 'J55'], 'K': ['K22', 'K33', 'K44', 'K55']}
    A   B   C   X
4  A4  B4  C4  X4
5  A5  B5  C5  X5
6  A6  B6  C6  X6
7  A7  B7  C7  X7
      H    U    J    K
22  H22  U22  J22  K22
33  H33  U33  J33  K33
44  H44  U44  J44  K44
55  H55  U55  J55  K55


In [592]:
pd.concat([df3,df6])

A    B    C    X    H    U    J    K
4    A4   B4   C4   X4  NaN  NaN  NaN  NaN
5    A5   B5   C5   X5  NaN  NaN  NaN  NaN
6    A6   B6   C6   X6  NaN  NaN  NaN  NaN
7    A7   B7   C7   X7  NaN  NaN  NaN  NaN
22  NaN  NaN  NaN  NaN  H22  U22  J22  K22
33  NaN  NaN  NaN  NaN  H33  U33  J33  K33
44  NaN  NaN  NaN  NaN  H44  U44  J44  K44
55  NaN  NaN  NaN  NaN  H55  U55  J55  K55

In [593]:
print(pd.concat([df3,df6],join = 'inner'))

Empty DataFrame
Columns: []
Index: [4, 5, 6, 7, 22, 33, 44, 55]


In [594]:
print(df1);print(df2); print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [595]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
 'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
 'hire_date': [2004, 2008, 2012, 2014]})
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [596]:
df3 = pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [597]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
 'supervisor': ['Carly', 'Guido', 'Steve']})
print(df3); print(df4); 

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


In [598]:
pd.merge(df3, df4)

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [599]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
 'Engineering', 'Engineering', 'HR', 'HR'],'skills': ['math', 'spreadsheets', 'coding', 'linux',
 'spreadsheets', 'organization']})

In [600]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [601]:
df5

group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [602]:
pd.merge(df1,df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [603]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
 'salary': [70000, 80000, 120000, 90000]})

In [604]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [605]:
df3

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [606]:
pd.merge(df1, df3, left_on="employee", right_on="name")

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [607]:
pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [608]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
df1a

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR

In [609]:
print(df2a)

          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


In [610]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [611]:
pd.merge(df1a,df2a,left_index = True,right_index=True)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [612]:
df1a.join(df2a)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [613]:
df3

name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [614]:
pd.merge(df1a,df3,left_index =True,right_on ='name')

group  name  salary
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

In [615]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
 'food': ['fish', 'beans', 'bread']},
 columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
 'drink': ['wine', 'beer']},
 columns=['name', 'drink'])
print(df6); print(df7); print(pd.merge(df6, df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
   name   food drink
0  Mary  bread  wine


In [616]:
df6

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [617]:
df7

name drink
0    Mary  wine
1  Joseph  beer

In [618]:
pd.merge(df6,df7)

name   food drink
0  Mary  bread  wine

In [619]:
pd.merge(df6,df7,how ='left')

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [620]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
 'rank': [1, 2, 3, 4]})

In [621]:
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
 'rank': [3, 1, 4, 2]})

In [622]:
df8

name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

In [623]:
df9

name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

In [624]:
pd.merge(df8,df9,on = 'name')

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [625]:
pd.merge(df8,df9,on = 'name',suffixes = ["_L","_R"])

name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [626]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [627]:
ser.sum()


2.811925491708157

In [628]:
ser.mean()

0.5623850983416314

In [629]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
 'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [630]:
df.groupby('key')

In [631]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [632]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
 'data': range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [633]:
df.groupby('key').aggregate(['min',np.median,max,sum])

data               
     min median max sum
key                    
A      0    1.5   3   3
B      1    2.5   4   5
C      2    3.5   5   7

In [634]:
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [635]:
df.groupby('key').transform(lambda x: x-x.mean())

data
0  -1.5
1  -1.5
2  -1.5
3   1.5
4   1.5
5   1.5

In [636]:
df.groupby('key').mean()

data
key      
A     1.5
B     2.5
C     3.5

In [637]:
df.mean()

data    2.5
dtype: float64

In [638]:
def norm_by_d(x):
    x

In [639]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
 'data1': range(6),
 'data2': rng.randint(0, 10, 6)},
 columns = ['key', 'data1', 'data2'])
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [640]:
l= [0,1,2,1,2,0]

In [641]:
df.groupby(l)

In [642]:
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [643]:
df.groupby(df['key']).sum()

data1  data2
key              
A        3      8
B        5      7
C        7     12

In [644]:
df2 = df.set_index('key')
df2

data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9

In [645]:
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonnt'}

In [646]:
df2.groupby(mapping).sum()

data1  data2
consonant      5      7
consonnt       7     12
vowel          3      8

In [647]:
df2

data1  data2
key              
A        0      5
B        1      0
C        2      3
A        3      3
B        4      7
C        5      9

In [648]:
df2.groupby(str.lower).mean()

data1  data2
a    1.5    4.0
b    2.5    3.5
c    3.5    6.0

In [649]:
df2.groupby([str.lower,mapping]).mean()

data1  data2
a vowel        1.5    4.0
b consonant    2.5    3.5
c consonnt     3.5    6.0

In [650]:
#Pivot Tables
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [651]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [652]:
titanic.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [653]:
titanic.shape

(891, 15)

In [654]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [655]:
titanic.groupby(['sex','class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [656]:
titanic.pivot_table('survived',index = 'sex',columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [657]:
age = pd.cut(titanic['age'], [0, 18, 80])
titanic.pivot_table('survived', ['sex', age], 'class')

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [658]:
fare = pd.qcut(titanic['fare'], 2)
titanic.pivot_table('survived', ['sex', age], [fare, 'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (0, 18]               NaN  1.000000  0.714286          0.909091   
       (18, 80]              NaN  0.880000  0.444444          0.972973   
male   (0, 18]               NaN  0.000000  0.260870          0.800000   
       (18, 80]              0.0  0.098039  0.125000          0.391304   

fare                                 
class              Second     Third  
sex    age                           
female (0, 18]   1.000000  0.318182  
       (18, 80]  0.914286  0.391304  
male   (0, 18]   0.818182  0.178571  
       (18, 80]  0.030303  0.192308

In [659]:
titanic.pivot_table(index='sex', columns='class',
 aggfunc={'survived':sum, 'fare':'mean'})

fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [660]:
titanic.pivot_table('survived', index='sex', columns='class', margins=True)

class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

In [661]:
#vecotrisied String
x = np.array([1,2,3,4,5,6,7])
x*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [662]:
data = ['peter', 'Paul', 'MARY', 'gUIDO']
[s.capitalize() for s in data]

['Peter', 'Paul', 'Mary', 'Guido']

In [663]:
data = ['peter', 'Paul','None','MARY', 'gUIDO']
[s.capitalize() for s in data]

['Peter', 'Paul', 'None', 'Mary', 'Guido']

In [664]:
names = pd.Series(data)
names

0    peter
1     Paul
2     None
3     MARY
4    gUIDO
dtype: object

In [665]:
names.str.capitalize()

0    Peter
1     Paul
2     None
3     Mary
4    Guido
dtype: object

In [666]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
 'Eric Idle', 'Terry Jones', 'Michael Palin'])
monte

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: object

In [667]:
monte.str.lower()

0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: object

In [668]:
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [669]:
monte.str.startswith('A')

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [670]:
monte.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object

In [671]:
monte.str.extract('([A-Za-z]+)')

0
0   Graham
1     John
2    Terry
3     Eric
4    Terry
5  Michael

In [672]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

In [673]:
monte.str[0:5]

0    Graha
1    John 
2    Terry
3    Eric 
4    Terry
5    Micha
dtype: object

In [674]:
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

In [675]:
full_monte = pd.DataFrame({'name': monte,
 'info': ['B|C|D', 'B|D', 'A|C', 'B|D', 'B|C',
 'B|C|D']})
full_monte

name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2   Terry Gilliam    A|C
3       Eric Idle    B|D
4     Terry Jones    B|C
5   Michael Palin  B|C|D

In [676]:
full_monte['info'].str.get_dummies('|')

A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

In [677]:
#Date and Time in Pandas 
from datetime import datetime
datetime(year = 2012,month = 9,day =15)

datetime.datetime(2012, 9, 15, 0, 0)

In [678]:
from dateutil import parser
date = parser.parse("4th of July ,2010")
date  

datetime.datetime(2010, 7, 4, 0, 0)

In [679]:
date.strftime('%A')

'Sunday'

In [680]:
date = np.array('2018-03-22',dtype = np.datetime64)
date

array('2018-03-22', dtype='datetime64[D]')

In [681]:
date + np.arange(12)

array(['2018-03-22', '2018-03-23', '2018-03-24', '2018-03-25',
       '2018-03-26', '2018-03-27', '2018-03-28', '2018-03-29',
       '2018-03-30', '2018-03-31', '2018-04-01', '2018-04-02'],
      dtype='datetime64[D]')

In [682]:
np.datetime64('2017-02-21')

numpy.datetime64('2017-02-21')

In [683]:
np.datetime64('2017-02-21 12:12')

numpy.datetime64('2017-02-21T12:12')

In [684]:
np.datetime64('2017-02-21 12:59:59.50','ns')

numpy.datetime64('2017-02-21T12:59:59.500000000')

In [685]:
date = pd.to_datetime('17th of september,2022')
date

Timestamp('2022-09-17 00:00:00')

In [686]:
date.strftime('%A')

'Saturday'

In [687]:
a = date+pd.to_timedelta(np.arange(12),'D')
a

DatetimeIndex(['2022-09-17', '2022-09-18', '2022-09-19', '2022-09-20',
               '2022-09-21', '2022-09-22', '2022-09-23', '2022-09-24',
               '2022-09-25', '2022-09-26', '2022-09-27', '2022-09-28'],
              dtype='datetime64[ns]', freq=None)

In [688]:
a.strftime('%A')

Index(['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday'],
      dtype='object')

In [689]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04',
 '2015-07-04', '2015-08-04'])
data = pd.Series([0,1,2,3],index = index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [692]:
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015',
 '2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[ns]', freq=None)

In [693]:
dates.to_period('D')

PeriodIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
             '2015-07-08'],
            dtype='period[D]', freq='D')

In [695]:
a =pd.date_range('2020-04-11','2020-04-20')

In [696]:
a.strftime("%A")

Index(['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday', 'Sunday', 'Monday'],
      dtype='object')

In [699]:
a =pd.date_range('2020-04-11',periods =5,freq = 'H')
a

DatetimeIndex(['2020-04-11 00:00:00', '2020-04-11 01:00:00',
               '2020-04-11 02:00:00', '2020-04-11 03:00:00',
               '2020-04-11 04:00:00'],
              dtype='datetime64[ns]', freq='H')

In [700]:
pd.timedelta_range(0,periods =8,freq='H')

TimedeltaIndex(['00:00:00', '01:00:00', '02:00:00', '03:00:00', '04:00:00',
                '05:00:00', '06:00:00', '07:00:00'],
               dtype='timedelta64[ns]', freq='H')

In [702]:
from pandas.tseries.offsets import BDay
pd.date_range('2015-07-12',periods=5,freq=BDay())

DatetimeIndex(['2015-07-13', '2015-07-14', '2015-07-15', '2015-07-16',
               '2015-07-17'],
              dtype='datetime64[ns]', freq='B')

In [720]:
rng = np.random.RandomState(42)
x = rng.rand(16)
y = rng.rand(16)
%timeit x + y

2.51 µs ± 39 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [721]:
mask = (x>0.5)&(y<0.5)

In [722]:
mask

array([False, False,  True,  True, False, False, False,  True,  True,
       False, False, False, False, False, False, False])

In [723]:
tmp1 = (x>0.5)
tmp2 = (y<0.5)
mask = tmp1&tmp2

In [724]:
import numexpr

ModuleNotFoundError: No module named 'numexpr'

In [725]:
import pandas as pd
nrows, ncols = 100000, 100
rng = np.random.RandomState(42)
df1, df2, df3, df4 = (pd.DataFrame(rng.rand(nrows, ncols))
 for i in range(4))

In [726]:
%timeit df1 + df2 + df3 + df4

709 ms ± 17.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [727]:
nrows

100000

In [728]:
ncols

100

In [729]:
df1, df2, df3, df4, df5 = (pd.DataFrame(rng.randint(0, 1000, (100, 3)))
 for i in range(5))

In [732]:
df3

0    1    2
0   912   97  806
1   766  714  218
2   502  508  541
3   562  195  277
4   200   24  113
..  ...  ...  ...
95  851  638  790
96   63  389  759
97  424  540  973
98   22  964  437
99  991  182  994

[100 rows x 3 columns]

In [733]:
df = pd.DataFrame(rng.rand(1000, 3), columns=['A', 'B', 'C'])
df.head()

A         B         C
0  0.375506  0.406939  0.069938
1  0.069087  0.235615  0.154374
2  0.677945  0.433839  0.652324
3  0.264038  0.808055  0.347197
4  0.589161  0.252418  0.557789